name: build
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches:
      - dev
      - main
jobs:
  execute-tests-ubuntu22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
        opam-disable-sandboxing: true
    - run: opam install -y ppx_deriving ocamlfind parmap batteries

    - name: Install apt requirements
      run: install/install_apt.sh

    - name: Test
      run: |
        sed -i "s/^      I.apply ~instrs:il' ~funcs:ufl' ~fname_callsites:fch in$/      il' in/" $(pwd)/src/ail.ml
        $(pwd)/test/test_action.sh

  execute-coreutils-ubuntu22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
        opam-disable-sandboxing: true
    - run: opam install -y ppx_deriving ocamlfind parmap batteries

    - name: Install apt requirements
      run: install/install_apt.sh

    - name: Install coreutils
      run: install/install_coreutils.sh

    - name: Test
      run: |
        sed -i "s/^      I.apply ~instrs:il' ~funcs:ufl' ~fname_callsites:fch in$/      il' in/" $(pwd)/src/ail.ml
        $(pwd)/test/test_coreutils.sh
 
 
  execute-tests-ubuntu24:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
        opam-disable-sandboxing: true
    - run: opam install -y ppx_deriving ocamlfind parmap batteries

    - name: Install apt requirements
      run: install/install_apt.sh

    - name: Test
      run: |
        sed -i "s/^      I.apply ~instrs:il' ~funcs:ufl' ~fname_callsites:fch in$/      il' in/" $(pwd)/src/ail.ml
        $(pwd)/test/test_action.sh

  execute-coreutils-ubuntu24:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
        opam-disable-sandboxing: true
    - run: opam install -y ppx_deriving ocamlfind parmap batteries

    - name: Install apt requirements
      run: install/install_apt.sh

    - name: Install coreutils
      run: install/install_coreutils.sh

    - name: Test
      run: |
        sed -i "s/^      I.apply ~instrs:il' ~funcs:ufl' ~fname_callsites:fch in$/      il' in/" $(pwd)/src/ail.ml
        $(pwd)/test/test_coreutils.sh

  execute-instrument-tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
        opam-disable-sandboxing: true
    - run: opam install -y ppx_deriving ocamlfind parmap batteries

    - name: Install apt requirements
      run: install/install_apt.sh

    - name: Instrument Test
      run: |
        $(pwd)/test/test_all.py -a -c
        $(pwd)/test/test_instrument.sh
